language: cpp
compiler:
  - gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "walker"
  skip_cleanup: true
  on:
    tags: true

before_script:
  - mkdir build
  - cd build

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake ..
  - cmake --build . --target walker